[package]
name = "webgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.15"
winit = "0.28"
wgpu_glyph = "0.19"
futures = "0.3"
regex = "1.7"
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
