export class Element {
  public readonly assignedSlot: string | undefined;
  public readonly attributes: Map<string, any> = new Map<string, any>();
  public readonly children: Element[] = [];
  public childrenCount: number;
  public readonly classList: Set<string> = new Set();
  public className: string;
  public readonly clientHeight: number;
  public readonly clientLeft: number;
  public readonly clientWidth: number;
  public readonly currentCSSZoom: number;
  public elementTiming: number;
  public id: string;
  public innerHTML: string;
  public readonly lastElementChild: Element | undefined;
  public readonly localName: string;
  public readonly namespaceURI: string | null;
  public readonly nextElementSibling: Element | undefined;
  public outerHTML: string;
  public part: Set<string>;
  public readonly prefix: string;
  public readonly previousElementSibling: Element | undefined;
  public readonly scrollHeight: number;
  public readonly scrollLeft: number;
  public readonly scrollTop: number;
  public readonly scrollWidth: number;
  public readonly shadowRoot: string | null;
  public slot: Element | undefined;
  public readonly tagName: string;

  public ariaAtomic: string | null = null;
  public ariaAutoComplete: boolean | null = null;
  public ariaBrailleLabel: string | null = null;
  public ariaBrailleRoleDescription: string | null = null;
  public ariaBusy: boolean | null = null;
  public ariaChecked: boolean | null = null;
  public ariaColCount: number | null = null;
  public ariaColIndex: number | null = null;
  public ariaColIndexText: string | null = null;
  public ariaCurrent: Element | null = null;
  public ariaDescription: string | null = null;
  public ariaDisabled: boolean | null = null;
  public ariaExpanded: boolean | null = null;
  public ariaHasPopup: boolean | null = null;
  public ariaHidden: boolean | null = null;
  public ariaKeyShortcuts: string | null = null;
  public ariaLabel: string | null = null;
  public ariaLevel: string | null = null;
  public ariaLive: string | null = null;
  public ariaModel: string | null = null;
  public ariaMultiline: string | null = null;
  public ariaMultiSelectable: boolean | null = null;
  public ariaOrientation: string | null = null;
  public ariaPlaceholder: string | null = null;
  public ariaPosInSet: number | null = null;
  public ariaPressed: boolean | null = null;
  public ariaReadOnly: boolean | null = null;
  public ariaRequired: boolean | null = null;
  public ariaRoleDescription: string | null = null;
  public ariaRowCount: number | null = null;
  public ariaRowIndex: number | null = null;
  public ariaRowIndexText: string | null = null;
  public ariaRowSpan: number | null = null;
  public ariaSelected: boolean | null = null;
  public ariaSetSize: number | null = null;
  public ariaSort: string | null = null;
  public ariaValueMax: number | null = null;
  public ariaValueMin: number | null = null;
  public ariaValueNow: number | null = null;
  public ariaValueText: string | null = null;
}
